using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sudoku_Solver
{
    public partial class SolvePage
    {
        public void ButtonClean()
        {
            Continue = true;
            Cell1_1.Content = "0"; Cell1_1.Background = TransBrush;
            Cell1_2.Content = "0"; Cell1_2.Background = TransBrush;
            Cell1_3.Content = "0"; Cell1_3.Background = TransBrush;
            Cell1_4.Content = "0"; Cell1_4.Background = TransBrush;
            Cell1_5.Content = "0"; Cell1_5.Background = TransBrush;
            Cell1_6.Content = "0"; Cell1_6.Background = TransBrush;
            Cell1_7.Content = "0"; Cell1_7.Background = TransBrush;
            Cell1_8.Content = "0"; Cell1_8.Background = TransBrush;
            Cell1_9.Content = "0"; Cell1_9.Background = TransBrush;
            Cell2_1.Content = "0"; Cell2_1.Background = TransBrush;
            Cell2_2.Content = "0"; Cell2_2.Background = TransBrush;
            Cell2_3.Content = "0"; Cell2_3.Background = TransBrush;
            Cell2_4.Content = "0"; Cell2_4.Background = TransBrush;
            Cell2_5.Content = "0"; Cell2_5.Background = TransBrush;
            Cell2_6.Content = "0"; Cell2_6.Background = TransBrush;
            Cell2_7.Content = "0"; Cell2_7.Background = TransBrush;
            Cell2_8.Content = "0"; Cell2_8.Background = TransBrush;
            Cell2_9.Content = "0"; Cell2_9.Background = TransBrush;
            Cell3_1.Content = "0"; Cell3_1.Background = TransBrush;
            Cell3_2.Content = "0"; Cell3_2.Background = TransBrush;
            Cell3_3.Content = "0"; Cell3_3.Background = TransBrush;
            Cell3_4.Content = "0"; Cell3_4.Background = TransBrush;
            Cell3_5.Content = "0"; Cell3_5.Background = TransBrush;
            Cell3_6.Content = "0"; Cell3_6.Background = TransBrush;
            Cell3_7.Content = "0"; Cell3_7.Background = TransBrush;
            Cell3_8.Content = "0"; Cell3_8.Background = TransBrush;
            Cell3_9.Content = "0"; Cell3_9.Background = TransBrush;
            Cell4_1.Content = "0"; Cell4_1.Background = TransBrush;
            Cell4_2.Content = "0"; Cell4_2.Background = TransBrush;
            Cell4_3.Content = "0"; Cell4_3.Background = TransBrush;
            Cell4_4.Content = "0"; Cell4_4.Background = TransBrush;
            Cell4_5.Content = "0"; Cell4_5.Background = TransBrush;
            Cell4_6.Content = "0"; Cell4_6.Background = TransBrush;
            Cell4_7.Content = "0"; Cell4_7.Background = TransBrush;
            Cell4_8.Content = "0"; Cell4_8.Background = TransBrush;
            Cell4_9.Content = "0"; Cell4_9.Background = TransBrush;
            Cell5_1.Content = "0"; Cell5_1.Background = TransBrush;
            Cell5_2.Content = "0"; Cell5_2.Background = TransBrush;
            Cell5_3.Content = "0"; Cell5_3.Background = TransBrush;
            Cell5_4.Content = "0"; Cell5_4.Background = TransBrush;
            Cell5_5.Content = "0"; Cell5_5.Background = TransBrush;
            Cell5_6.Content = "0"; Cell5_6.Background = TransBrush;
            Cell5_7.Content = "0"; Cell5_7.Background = TransBrush;
            Cell5_8.Content = "0"; Cell5_8.Background = TransBrush;
            Cell5_9.Content = "0"; Cell5_9.Background = TransBrush;
            Cell6_1.Content = "0"; Cell6_1.Background = TransBrush;
            Cell6_2.Content = "0"; Cell6_2.Background = TransBrush;
            Cell6_3.Content = "0"; Cell6_3.Background = TransBrush;
            Cell6_4.Content = "0"; Cell6_4.Background = TransBrush;
            Cell6_5.Content = "0"; Cell6_5.Background = TransBrush;
            Cell6_6.Content = "0"; Cell6_6.Background = TransBrush;
            Cell6_7.Content = "0"; Cell6_7.Background = TransBrush;
            Cell6_8.Content = "0"; Cell6_8.Background = TransBrush;
            Cell6_9.Content = "0"; Cell6_9.Background = TransBrush;
            Cell7_1.Content = "0"; Cell7_1.Background = TransBrush;
            Cell7_2.Content = "0"; Cell7_2.Background = TransBrush;
            Cell7_3.Content = "0"; Cell7_3.Background = TransBrush;
            Cell7_4.Content = "0"; Cell7_4.Background = TransBrush;
            Cell7_5.Content = "0"; Cell7_5.Background = TransBrush;
            Cell7_6.Content = "0"; Cell7_6.Background = TransBrush;
            Cell7_7.Content = "0"; Cell7_7.Background = TransBrush;
            Cell7_8.Content = "0"; Cell7_8.Background = TransBrush;
            Cell7_9.Content = "0"; Cell7_9.Background = TransBrush;
            Cell8_1.Content = "0"; Cell8_1.Background = TransBrush;
            Cell8_2.Content = "0"; Cell8_2.Background = TransBrush;
            Cell8_3.Content = "0"; Cell8_3.Background = TransBrush;
            Cell8_4.Content = "0"; Cell8_4.Background = TransBrush;
            Cell8_5.Content = "0"; Cell8_5.Background = TransBrush;
            Cell8_6.Content = "0"; Cell8_6.Background = TransBrush;
            Cell8_7.Content = "0"; Cell8_7.Background = TransBrush;
            Cell8_8.Content = "0"; Cell8_8.Background = TransBrush;
            Cell8_9.Content = "0"; Cell8_9.Background = TransBrush;
            Cell9_1.Content = "0"; Cell9_1.Background = TransBrush;
            Cell9_2.Content = "0"; Cell9_2.Background = TransBrush;
            Cell9_3.Content = "0"; Cell9_3.Background = TransBrush;
            Cell9_4.Content = "0"; Cell9_4.Background = TransBrush;
            Cell9_5.Content = "0"; Cell9_5.Background = TransBrush;
            Cell9_6.Content = "0"; Cell9_6.Background = TransBrush;
            Cell9_7.Content = "0"; Cell9_7.Background = TransBrush;
            Cell9_8.Content = "0"; Cell9_8.Background = TransBrush;
            Cell9_9.Content = "0"; Cell9_9.Background = TransBrush;
            ButtonToArray();
        }
        public void ButtonToArray()
        {
            ArrayA[1, 1] = int.Parse((Cell1_1.Content.ToString()));
            ArrayA[1, 2] = int.Parse((Cell1_2.Content.ToString()));
            ArrayA[1, 3] = int.Parse((Cell1_3.Content.ToString()));
            ArrayA[1, 4] = int.Parse((Cell1_4.Content.ToString()));
            ArrayA[1, 5] = int.Parse((Cell1_5.Content.ToString()));
            ArrayA[1, 6] = int.Parse((Cell1_6.Content.ToString()));
            ArrayA[1, 7] = int.Parse((Cell1_7.Content.ToString()));
            ArrayA[1, 8] = int.Parse((Cell1_8.Content.ToString()));
            ArrayA[1, 9] = int.Parse((Cell1_9.Content.ToString()));
            ArrayA[2, 1] = int.Parse((Cell2_1.Content.ToString()));
            ArrayA[2, 2] = int.Parse((Cell2_2.Content.ToString()));
            ArrayA[2, 3] = int.Parse((Cell2_3.Content.ToString()));
            ArrayA[2, 4] = int.Parse((Cell2_4.Content.ToString()));
            ArrayA[2, 5] = int.Parse((Cell2_5.Content.ToString()));
            ArrayA[2, 6] = int.Parse((Cell2_6.Content.ToString()));
            ArrayA[2, 7] = int.Parse((Cell2_7.Content.ToString()));
            ArrayA[2, 8] = int.Parse((Cell2_8.Content.ToString()));
            ArrayA[2, 9] = int.Parse((Cell2_9.Content.ToString()));
            ArrayA[3, 1] = int.Parse((Cell3_1.Content.ToString()));
            ArrayA[3, 2] = int.Parse((Cell3_2.Content.ToString()));
            ArrayA[3, 3] = int.Parse((Cell3_3.Content.ToString()));
            ArrayA[3, 4] = int.Parse((Cell3_4.Content.ToString()));
            ArrayA[3, 5] = int.Parse((Cell3_5.Content.ToString()));
            ArrayA[3, 6] = int.Parse((Cell3_6.Content.ToString()));
            ArrayA[3, 7] = int.Parse((Cell3_7.Content.ToString()));
            ArrayA[3, 8] = int.Parse((Cell3_8.Content.ToString()));
            ArrayA[3, 9] = int.Parse((Cell3_9.Content.ToString()));
            ArrayA[4, 1] = int.Parse((Cell4_1.Content.ToString()));
            ArrayA[4, 2] = int.Parse((Cell4_2.Content.ToString()));
            ArrayA[4, 3] = int.Parse((Cell4_3.Content.ToString()));
            ArrayA[4, 4] = int.Parse((Cell4_4.Content.ToString()));
            ArrayA[4, 5] = int.Parse((Cell4_5.Content.ToString()));
            ArrayA[4, 6] = int.Parse((Cell4_6.Content.ToString()));
            ArrayA[4, 7] = int.Parse((Cell4_7.Content.ToString()));
            ArrayA[4, 8] = int.Parse((Cell4_8.Content.ToString()));
            ArrayA[4, 9] = int.Parse((Cell4_9.Content.ToString()));
            ArrayA[5, 1] = int.Parse((Cell5_1.Content.ToString()));
            ArrayA[5, 2] = int.Parse((Cell5_2.Content.ToString()));
            ArrayA[5, 3] = int.Parse((Cell5_3.Content.ToString()));
            ArrayA[5, 4] = int.Parse((Cell5_4.Content.ToString()));
            ArrayA[5, 5] = int.Parse((Cell5_5.Content.ToString()));
            ArrayA[5, 6] = int.Parse((Cell5_6.Content.ToString()));
            ArrayA[5, 7] = int.Parse((Cell5_7.Content.ToString()));
            ArrayA[5, 8] = int.Parse((Cell5_8.Content.ToString()));
            ArrayA[5, 9] = int.Parse((Cell5_9.Content.ToString()));
            ArrayA[6, 1] = int.Parse((Cell6_1.Content.ToString()));
            ArrayA[6, 2] = int.Parse((Cell6_2.Content.ToString()));
            ArrayA[6, 3] = int.Parse((Cell6_3.Content.ToString()));
            ArrayA[6, 4] = int.Parse((Cell6_4.Content.ToString()));
            ArrayA[6, 5] = int.Parse((Cell6_5.Content.ToString()));
            ArrayA[6, 6] = int.Parse((Cell6_6.Content.ToString()));
            ArrayA[6, 7] = int.Parse((Cell6_7.Content.ToString()));
            ArrayA[6, 8] = int.Parse((Cell6_8.Content.ToString()));
            ArrayA[6, 9] = int.Parse((Cell6_9.Content.ToString()));
            ArrayA[7, 1] = int.Parse((Cell7_1.Content.ToString()));
            ArrayA[7, 2] = int.Parse((Cell7_2.Content.ToString()));
            ArrayA[7, 3] = int.Parse((Cell7_3.Content.ToString()));
            ArrayA[7, 4] = int.Parse((Cell7_4.Content.ToString()));
            ArrayA[7, 5] = int.Parse((Cell7_5.Content.ToString()));
            ArrayA[7, 6] = int.Parse((Cell7_6.Content.ToString()));
            ArrayA[7, 7] = int.Parse((Cell7_7.Content.ToString()));
            ArrayA[7, 8] = int.Parse((Cell7_8.Content.ToString()));
            ArrayA[7, 9] = int.Parse((Cell7_9.Content.ToString()));
            ArrayA[8, 1] = int.Parse((Cell8_1.Content.ToString()));
            ArrayA[8, 2] = int.Parse((Cell8_2.Content.ToString()));
            ArrayA[8, 3] = int.Parse((Cell8_3.Content.ToString()));
            ArrayA[8, 4] = int.Parse((Cell8_4.Content.ToString()));
            ArrayA[8, 5] = int.Parse((Cell8_5.Content.ToString()));
            ArrayA[8, 6] = int.Parse((Cell8_6.Content.ToString()));
            ArrayA[8, 7] = int.Parse((Cell8_7.Content.ToString()));
            ArrayA[8, 8] = int.Parse((Cell8_8.Content.ToString()));
            ArrayA[8, 9] = int.Parse((Cell8_9.Content.ToString()));
            ArrayA[9, 1] = int.Parse((Cell9_1.Content.ToString()));
            ArrayA[9, 2] = int.Parse((Cell9_2.Content.ToString()));
            ArrayA[9, 3] = int.Parse((Cell9_3.Content.ToString()));
            ArrayA[9, 4] = int.Parse((Cell9_4.Content.ToString()));
            ArrayA[9, 5] = int.Parse((Cell9_5.Content.ToString()));
            ArrayA[9, 6] = int.Parse((Cell9_6.Content.ToString()));
            ArrayA[9, 7] = int.Parse((Cell9_7.Content.ToString()));
            ArrayA[9, 8] = int.Parse((Cell9_8.Content.ToString()));
            ArrayA[9, 9] = int.Parse((Cell9_9.Content.ToString()));
        }
        public void ArrayToButton()
        {
            Cell1_1.Content = ArrayA[1, 1].ToString();
            Cell1_2.Content = ArrayA[1, 2].ToString();
            Cell1_3.Content = ArrayA[1, 3].ToString();
            Cell1_4.Content = ArrayA[1, 4].ToString();
            Cell1_5.Content = ArrayA[1, 5].ToString();
            Cell1_6.Content = ArrayA[1, 6].ToString();
            Cell1_7.Content = ArrayA[1, 7].ToString();
            Cell1_8.Content = ArrayA[1, 8].ToString();
            Cell1_9.Content = ArrayA[1, 9].ToString();
            Cell2_1.Content = ArrayA[2, 1].ToString();
            Cell2_2.Content = ArrayA[2, 2].ToString();
            Cell2_3.Content = ArrayA[2, 3].ToString();
            Cell2_4.Content = ArrayA[2, 4].ToString();
            Cell2_5.Content = ArrayA[2, 5].ToString();
            Cell2_6.Content = ArrayA[2, 6].ToString();
            Cell2_7.Content = ArrayA[2, 7].ToString();
            Cell2_8.Content = ArrayA[2, 8].ToString();
            Cell2_9.Content = ArrayA[2, 9].ToString();
            Cell3_1.Content = ArrayA[3, 1].ToString();
            Cell3_2.Content = ArrayA[3, 2].ToString();
            Cell3_3.Content = ArrayA[3, 3].ToString();
            Cell3_4.Content = ArrayA[3, 4].ToString();
            Cell3_5.Content = ArrayA[3, 5].ToString();
            Cell3_6.Content = ArrayA[3, 6].ToString();
            Cell3_7.Content = ArrayA[3, 7].ToString();
            Cell3_8.Content = ArrayA[3, 8].ToString();
            Cell3_9.Content = ArrayA[3, 9].ToString();
            Cell4_1.Content = ArrayA[4, 1].ToString();
            Cell4_2.Content = ArrayA[4, 2].ToString();
            Cell4_3.Content = ArrayA[4, 3].ToString();
            Cell4_4.Content = ArrayA[4, 4].ToString();
            Cell4_5.Content = ArrayA[4, 5].ToString();
            Cell4_6.Content = ArrayA[4, 6].ToString();
            Cell4_7.Content = ArrayA[4, 7].ToString();
            Cell4_8.Content = ArrayA[4, 8].ToString();
            Cell4_9.Content = ArrayA[4, 9].ToString();
            Cell5_1.Content = ArrayA[5, 1].ToString();
            Cell5_2.Content = ArrayA[5, 2].ToString();
            Cell5_3.Content = ArrayA[5, 3].ToString();
            Cell5_4.Content = ArrayA[5, 4].ToString();
            Cell5_5.Content = ArrayA[5, 5].ToString();
            Cell5_6.Content = ArrayA[5, 6].ToString();
            Cell5_7.Content = ArrayA[5, 7].ToString();
            Cell5_8.Content = ArrayA[5, 8].ToString();
            Cell5_9.Content = ArrayA[5, 9].ToString();
            Cell6_1.Content = ArrayA[6, 1].ToString();
            Cell6_2.Content = ArrayA[6, 2].ToString();
            Cell6_3.Content = ArrayA[6, 3].ToString();
            Cell6_4.Content = ArrayA[6, 4].ToString();
            Cell6_5.Content = ArrayA[6, 5].ToString();
            Cell6_6.Content = ArrayA[6, 6].ToString();
            Cell6_7.Content = ArrayA[6, 7].ToString();
            Cell6_8.Content = ArrayA[6, 8].ToString();
            Cell6_9.Content = ArrayA[6, 9].ToString();
            Cell7_1.Content = ArrayA[7, 1].ToString();
            Cell7_2.Content = ArrayA[7, 2].ToString();
            Cell7_3.Content = ArrayA[7, 3].ToString();
            Cell7_4.Content = ArrayA[7, 4].ToString();
            Cell7_5.Content = ArrayA[7, 5].ToString();
            Cell7_6.Content = ArrayA[7, 6].ToString();
            Cell7_7.Content = ArrayA[7, 7].ToString();
            Cell7_8.Content = ArrayA[7, 8].ToString();
            Cell7_9.Content = ArrayA[7, 9].ToString();
            Cell8_1.Content = ArrayA[8, 1].ToString();
            Cell8_2.Content = ArrayA[8, 2].ToString();
            Cell8_3.Content = ArrayA[8, 3].ToString();
            Cell8_4.Content = ArrayA[8, 4].ToString();
            Cell8_5.Content = ArrayA[8, 5].ToString();
            Cell8_6.Content = ArrayA[8, 6].ToString();
            Cell8_7.Content = ArrayA[8, 7].ToString();
            Cell8_8.Content = ArrayA[8, 8].ToString();
            Cell8_9.Content = ArrayA[8, 9].ToString();
            Cell9_1.Content = ArrayA[9, 1].ToString();
            Cell9_2.Content = ArrayA[9, 2].ToString();
            Cell9_3.Content = ArrayA[9, 3].ToString();
            Cell9_4.Content = ArrayA[9, 4].ToString();
            Cell9_5.Content = ArrayA[9, 5].ToString();
            Cell9_6.Content = ArrayA[9, 6].ToString();
            Cell9_7.Content = ArrayA[9, 7].ToString();
            Cell9_8.Content = ArrayA[9, 8].ToString();
            Cell9_9.Content = ArrayA[9, 9].ToString();

        }
    }
}
